### ISSUE TITLE
Make anchor tags go somewhere

### ISSUE THREAD

**Issue by Timer** [Timer/create-react-app#13]
Let's make anchor tags open in the editor or (better yet) chrome dev tools.

Let me know if you're interested!

**Comment by huhwhat777** [comment]
I love to figure something out and help r guldance is what I need if I see it done will help me a lot

**Comment by Timer** [comment]
Hey!
This issue has been moved to https://github.com/facebookincubator/create-react-app/issues/2110, which provides some context on what needs to be done.

We can talk about it over there. 😄

**Comment by huhwhat777** [comment]
Yes I'm vary inserted but don't know nothing
